name: website

on: push

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v1
    - name: Build
      run: |
          echo REACT_APP_URL=https://internhacks.com > .env
          npm install
          npm run lint
          npm run build
    - name: Deploy
      if: success()
      uses: crazy-max/ghaction-github-pages@v1
      with:
        target_branch: gh-pages
        build_dir: build
        fqdn: internhacks.com
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
